[package]
name = "majin-desktop"
description = "majin desktop application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "majin_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
majin-protocol = { workspace = true }
majin-pty = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
tauri = { version = "2", features = [] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
